name: Build and Test

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.txt'
      - '**/*.md'
  pull_request:
    branches: [ master ] 
    
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
  
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore 
      
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
      
   # - name: Publish Test Results
   #   uses: dorny/test-reporter@v1.5.0
   #   if: success() || failure()
   #   with: 
   #     name: Test Result View
   #     path: 
    
    
    - name: dotnet-tests-report
      id: testAction3a
      # You may pin to the exact commit or the version.
      # uses: zyborg/dotnet-tests-report@ce730c068bb73480dcb37c02d40890bf8b44c953
      uses: zyborg/dotnet-tests-report@v1.4.4
      with:
          report_name: Api Demo Test Report
          report_title: Api Demo Test Report
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
    - name: dump test results
      shell: pwsh
      run: |
          Write-ActionInfo '    * result_value    = ${{ steps.testAction3a.outputs.result_value }}'
          Write-ActionInfo '    * total_count     = ${{ steps.testAction3a.outputs.total_count }}'
          Write-ActionInfo '    * passed_count    = ${{ steps.testAction3a.outputs.passed_count }}'
          Write-ActionInfo '    * failed_count    = ${{ steps.testAction3a.outputs.failed_count }}'
          Write-ActionInfo '    * gist_report_url = ${{ steps.testAction3a.outputs.gist_report_url }}'
          Write-ActionInfo '    * gist_badge_url  = ${{ steps.testAction3a.outputs.gist_badge_url }}'




  
      
