name: Build and Test

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.txt'
      - '**/*.md'
  pull_request:
    branches: [ master ] 
    
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
  
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
        
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: csharp
        queries: +security-and-quality
        packs: +scope/pack1,scope/pack2@v1.2.3
        
    - name: Sonarqube Begin
      run: | 
        dotnet tool install --global dotnet-sonarscanner
        dotnet tool install --global dotnet-reportgenerator-globaltool
        dotnet sonarscanner begin /k:"drArqon_ejDemoApi" /o:"drarqon" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" 
        
      #/d:sonar.coverageReportPaths="./sonarqubecoverage/SonarQube.xml"

        
        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore 
      
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

      
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
      
   # - name: Publish Test Results
   #   uses: dorny/test-reporter@v1.5.0
   #   if: success() || failure()
   #   with: 
   #     name: Test Result View
   #     path: 
    
    
    - name: dotnet-tests-report
      uses: zyborg/dotnet-tests-report@v1.4.4
      with:
          project_path: ejDemoApi.Tests
          report_name: dotnet-tests-report
          report_title: dotnet-tests-report
          github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: dotnet-integration-tests-report
      uses: zyborg/dotnet-tests-report@v1.4.4
      with:
          project_path: ejDemoApi.Integration
          report_name: dotnet-integration-tests-report
          report_title: dotnet-integration-tests-report
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Sonarqube end
      run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   
      
